'use client';
import {useEffect,useState} from 'react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend} from 'recharts';
import {ChevronLeft,ChevronRight} from 'lucide-react';
import {readRange} from '@/lib/read-rows';
import {dateKey,fromKey,shiftDay,durationLabel} from '@/lib/dates';
import {weeklyRows} from '@/lib/weekly';
import type {Meal,Sleep} from '@/lib/types';
export default function WeeklyCharts({userId,day,onDay,version}:{userId:string;day:string;onDay:(day:string)=>void;version:number}) {
  const start=shiftDay(day,-((fromKey(day).getDay()+6)%7)),end=shiftDay(start,6);
  const [rows,setRows]=useState<ReturnType<typeof weeklyRows>>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [retry,setRetry]=useState(0);
  useEffect(()=>{
    let active=true;setLoading(true);setRows([]);setError('');
    Promise.all([readRange<Meal>('meals',userId,start,end),readRange<Sleep>('sleep_logs',userId,start,end)]).then(([meals,sleep])=>{if(active)setRows(weeklyRows(Array.from({length:7},(_,i)=>shiftDay(start,i)),meals,sleep));}).catch(()=>{if(active)setError('Could not load your week. Please try again.');}).finally(()=>{if(active)setLoading(false);});
    return()=>{active=false;};
  },[userId,start,end,version,retry]);
  const nights=rows.filter(r=>r.sleepHours!==null);const total=rows.reduce((sum,r)=>sum+r.total,0);const average=nights.length?nights.reduce((sum,r)=>sum+r.sleepHours!,0)*60/nights.length:null;
  const label=(value:string)=>fromKey(value).toLocaleDateString([],{weekday:'short'});
  return <section aria-label="Weekly insights"><div className="week-controls"><button className="icon-button" aria-label="Previous week" onClick={()=>onDay(shiftDay(start,-7))}><ChevronLeft/></button><div><span className="eyebrow">MONDAY TO SUNDAY</span><h2>{fromKey(start).toLocaleDateString([],{month:'short',day:'numeric'})} – {fromKey(end).toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'})}</h2></div><button className="icon-button" aria-label="Next week" onClick={()=>onDay(shiftDay(start,7))}><ChevronRight/></button><button className="text-button" onClick={()=>onDay(dateKey(new Date()))}>This week</button></div>
    {error&&<p role="alert" className="error">{error}<button className="text-button" onClick={()=>setRetry(n=>n+1)}>Retry charts</button></p>}
    {loading?<p role="status">Finding your weekly rhythm…</p>:!error&&<><div className="weekly-stats"><div><span>MEALS LOGGED</span><strong>{total}<small> colorful moments</small></strong></div><div><span>AVERAGE SLEEP</span><strong>{average===null?'—':durationLabel(average)}<small> {nights.length} nights recorded</small></strong></div></div>
    <div className="charts-grid"><article className="chart-card"><div className="chart-title"><h3>A plate-by-plate picture</h3><span aria-hidden="true">🍊</span></div><p>Meals each day, grouped by type.</p><div className="chart-container" role="img" aria-label="Stacked bar chart of meals per day by meal type; exact values in weekly data below"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{left:-20,right:10,top:8,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="3 4" stroke="#e5deed"/><XAxis dataKey="day" tickFormatter={label} tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={value=>String(value)} contentStyle={{borderRadius:14}}/><Legend wrapperStyle={{fontSize:11}}/>{(['breakfast','lunch','dinner','snack'] as const).map((type,i)=><Bar key={type} dataKey={type} name={type[0].toUpperCase()+type.slice(1)} stackId="meals" fill={['#89ad31','#dd78a8','#8151dc','#eba744'][i]} maxBarSize={34} isAnimationActive={false}/>)}</BarChart></ResponsiveContainer></div></article>
    <article className="chart-card"><div className="chart-title"><h3>Your recharge rhythm</h3><span aria-hidden="true">🌙</span></div><p>Hours of sleep, shown on your wake-up day.</p><div className="chart-container" role="img" aria-label="Bar chart of nightly sleep hours; exact values in weekly data below"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{left:-20,right:10,top:8,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="3 4" stroke="#e5deed"/><XAxis dataKey="day" tickFormatter={label} tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis domain={[0,'auto']} unit="h" tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={value=>String(value)} formatter={value=>[durationLabel(Number(value)*60),'Sleep']} contentStyle={{borderRadius:14}}/><Bar dataKey="sleepHours" name="Sleep hours" fill="#8151dc" radius={[8,8,0,0]} maxBarSize={34} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><p className="fine">A gap means no sleep log. It never counts as zero in your average.</p></article></div>
    <details className="data-table"><summary>View exact weekly data</summary><div className="table-scroll"><table><caption>Meals and sleep for the selected week</caption><thead><tr><th scope="col">Date</th><th scope="col">Breakfast</th><th scope="col">Lunch</th><th scope="col">Dinner</th><th scope="col">Snack</th><th scope="col">Sleep</th></tr></thead><tbody>{rows.map(row=><tr key={row.day}><th scope="row">{row.day}</th><td>{row.breakfast}</td><td>{row.lunch}</td><td>{row.dinner}</td><td>{row.snack}</td><td>{row.sleepHours===null?'Not logged':durationLabel(row.sleepHours*60)}</td></tr>)}</tbody></table></div></details></>}
  </section>;
}
